### ISSUE TITLE
Makes parameter management more flexible

### ISSUE THREAD

**Issue by mcappadonna** [redrob101/perl-ft#1]
In order to have cleaner code and makes eventually changes in parameters more fast, all the final ```if``` section can be replaced using ```foreach``` and a simplified ```if``` structure

```perl
foreach my $i (0..scalar(@ARGV)-1) {
    if (....) {
    } elsif (...) {
    }
    shift
}
```

 or, if possible, with something more advanced like [Getopt::Long](https://perldoc.perl.org/Getopt::Long).

**Comment by redrob101** [comment]
Used Getopt::Long to handle parameters in a simpler and more efficient way.
Thanks.
