### ISSUE TITLE
Some suggestions for future evolutions 

### ISSUE THREAD

**Issue by rascasoft** [redrob101/perl-ft#1]
Enable parameters so that a user can:

- Pass file or files to be transferred;
- Pass a specific ssh private key to be used in the ssh connection;
- Chose with tool to be used for the copy (scp or sftp);

**Comment by rascasoft** [comment]
It would be also useful having also all the host parameters as arguments in the command line.

**Comment by redrob101** [comment]
FTv3.pl fulfills requirements
