### ISSUE TITLE
Check if SSH/SFTP port is reachable

### ISSUE THREAD

**Issue by mcappadonna** [redrob101/perl-ft#2]
```perl
sub check_avail { 
    my $p = Net::Ping->new();
    $p->ping($host) or die "Host is unreachable...";
    $p->close();
}
```

Considering this script will transfer files over the port 22/tcp, checking if the remote host is pingable isn't the best way to proceed because often ping responses are disabled. Checking the reachability of the interested ports must be done instead.

**Comment by redrob101** [comment]
check_avail{} sub has been corrected. Now it checks if port 22 is reachable.
